spring:
  application:
    name: holiday-detail-service

server:
  port: 8080

nager:
  api:
    max-retries: 3
    holiday:
      http:
        connect-timeout: 45
        response-timeout: 30
    retry:
      maxAttempts: 3
      delay: 2000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.accenture.assignment.holiday
  paths-to-match: /api/v1/**

logging:
  level:
    com.accenture.assignment.holiday: INFO
    org.springframework.web: INFO